/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Mike
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {

        
        
        initComponents();
        returnDateChooser.setVisible(false);

        /*
        JSpinner.DateEditor de1 = new JSpinner.DateEditor(jSpinner1, "hh:mm a");
        de1.getTextField().setEditable(false);
        jSpinner1.setEditor(de1);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toggleButtonOneWay = new javax.swing.JToggleButton();
        toggleButtonRoundTrip = new javax.swing.JToggleButton();
        toggleButtonCoachSeating = new javax.swing.JToggleButton();
        toggleButtonFirstClassSeating = new javax.swing.JToggleButton();
        textFieldDepartureLocation = new JGhostTextField("Departure Location");
        textFieldArrivalLocation = new JGhostTextField("Arrivial Location");
        departureDateChooser = new com.toedter.calendar.JDateChooser();
        returnDateChooser = new com.toedter.calendar.JDateChooser();
        timeDepartStart = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        timeDepartEnd = new javax.swing.JSpinner();
        jPanel1 = new TimeInputPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toggleButtonOneWay.setSelected(true);
        toggleButtonOneWay.setText("One-Way");
        toggleButtonOneWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonOneWayActionPerformed(evt);
            }
        });

        toggleButtonRoundTrip.setText("Round-Trip");
        toggleButtonRoundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonRoundTripActionPerformed(evt);
            }
        });

        toggleButtonCoachSeating.setSelected(true);
        toggleButtonCoachSeating.setText("Coach Seating");
        toggleButtonCoachSeating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonCoachSeatingActionPerformed(evt);
            }
        });

        toggleButtonFirstClassSeating.setText("First Class Seating");
        toggleButtonFirstClassSeating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonFirstClassSeatingActionPerformed(evt);
            }
        });

        textFieldDepartureLocation.setToolTipText("");

        timeDepartStart.setModel(new SpinnerDateModel(new Date(), null, null, Calendar.MINUTE));
        timeDepartStart.setEditor(new JSpinner.DateEditor(timeDepartStart, "hh:mm a"));
        timeDepartStart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timeDepartStart.setFocusable(false);

        jTextField1.setEditable(false);
        jTextField1.setText("-");
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        timeDepartEnd.setModel(new SpinnerDateModel(new Date(), null, null, Calendar.MINUTE));
        timeDepartEnd.setEditor(new JSpinner.DateEditor(timeDepartEnd, "hh:mm a"));
        timeDepartEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timeDepartEnd.setFocusable(false);

        jPanel1.setVisible(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(departureDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(toggleButtonOneWay)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(toggleButtonRoundTrip))
                        .addComponent(textFieldDepartureLocation, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeDepartStart, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeDepartEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleButtonCoachSeating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleButtonFirstClassSeating))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textFieldArrivalLocation, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(returnDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleButtonOneWay)
                    .addComponent(toggleButtonRoundTrip)
                    .addComponent(toggleButtonCoachSeating)
                    .addComponent(toggleButtonFirstClassSeating))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDepartureLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldArrivalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(departureDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeDepartStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeDepartEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtonOneWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonOneWayActionPerformed
        toggleButtonOneWay.setSelected(true);
        toggleButtonRoundTrip.setSelected(false);
        returnDateChooser.setVisible(false);
      
    }//GEN-LAST:event_toggleButtonOneWayActionPerformed

    private void toggleButtonCoachSeatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonCoachSeatingActionPerformed
        toggleButtonFirstClassSeating.setSelected(false);
        toggleButtonCoachSeating.setSelected(true);
    }//GEN-LAST:event_toggleButtonCoachSeatingActionPerformed

    private void toggleButtonRoundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonRoundTripActionPerformed
        toggleButtonOneWay.setSelected(false);
        toggleButtonRoundTrip.setSelected(true);
        returnDateChooser.setVisible(true);
    }//GEN-LAST:event_toggleButtonRoundTripActionPerformed

    private void toggleButtonFirstClassSeatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonFirstClassSeatingActionPerformed
        toggleButtonFirstClassSeating.setSelected(true);
        toggleButtonCoachSeating.setSelected(false);
    }//GEN-LAST:event_toggleButtonFirstClassSeatingActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser departureDateChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser returnDateChooser;
    private javax.swing.JTextField textFieldArrivalLocation;
    private javax.swing.JTextField textFieldDepartureLocation;
    private javax.swing.JSpinner timeDepartEnd;
    private javax.swing.JSpinner timeDepartStart;
    private javax.swing.JToggleButton toggleButtonCoachSeating;
    private javax.swing.JToggleButton toggleButtonFirstClassSeating;
    private javax.swing.JToggleButton toggleButtonOneWay;
    private javax.swing.JToggleButton toggleButtonRoundTrip;
    // End of variables declaration//GEN-END:variables
}
